// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/gfalcon.proto

package gfalcon

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type SignInRequest struct {
	Team                 string   `protobuf:"bytes,1,opt,name=team,proto3" json:"team,omitempty"`
	Id                   string   `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Password             string   `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignInRequest) Reset()         { *m = SignInRequest{} }
func (m *SignInRequest) String() string { return proto.CompactTextString(m) }
func (*SignInRequest) ProtoMessage()    {}
func (*SignInRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_gfalcon_4975e5dad6958583, []int{0}
}
func (m *SignInRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignInRequest.Unmarshal(m, b)
}
func (m *SignInRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignInRequest.Marshal(b, m, deterministic)
}
func (dst *SignInRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignInRequest.Merge(dst, src)
}
func (m *SignInRequest) XXX_Size() int {
	return xxx_messageInfo_SignInRequest.Size(m)
}
func (m *SignInRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SignInRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SignInRequest proto.InternalMessageInfo

func (m *SignInRequest) GetTeam() string {
	if m != nil {
		return m.Team
	}
	return ""
}

func (m *SignInRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *SignInRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type SignInResponse struct {
	Ok                   bool     `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Iid                  uint32   `protobuf:"varint,2,opt,name=iid,proto3" json:"iid,omitempty"`
	Session              string   `protobuf:"bytes,3,opt,name=session,proto3" json:"session,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignInResponse) Reset()         { *m = SignInResponse{} }
func (m *SignInResponse) String() string { return proto.CompactTextString(m) }
func (*SignInResponse) ProtoMessage()    {}
func (*SignInResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_gfalcon_4975e5dad6958583, []int{1}
}
func (m *SignInResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignInResponse.Unmarshal(m, b)
}
func (m *SignInResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignInResponse.Marshal(b, m, deterministic)
}
func (dst *SignInResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignInResponse.Merge(dst, src)
}
func (m *SignInResponse) XXX_Size() int {
	return xxx_messageInfo_SignInResponse.Size(m)
}
func (m *SignInResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SignInResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SignInResponse proto.InternalMessageInfo

func (m *SignInResponse) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

func (m *SignInResponse) GetIid() uint32 {
	if m != nil {
		return m.Iid
	}
	return 0
}

func (m *SignInResponse) GetSession() string {
	if m != nil {
		return m.Session
	}
	return ""
}

type ValidateRequest struct {
	Iid                  uint32   `protobuf:"varint,1,opt,name=iid,proto3" json:"iid,omitempty"`
	Session              string   `protobuf:"bytes,2,opt,name=session,proto3" json:"session,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ValidateRequest) Reset()         { *m = ValidateRequest{} }
func (m *ValidateRequest) String() string { return proto.CompactTextString(m) }
func (*ValidateRequest) ProtoMessage()    {}
func (*ValidateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_gfalcon_4975e5dad6958583, []int{2}
}
func (m *ValidateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ValidateRequest.Unmarshal(m, b)
}
func (m *ValidateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ValidateRequest.Marshal(b, m, deterministic)
}
func (dst *ValidateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValidateRequest.Merge(dst, src)
}
func (m *ValidateRequest) XXX_Size() int {
	return xxx_messageInfo_ValidateRequest.Size(m)
}
func (m *ValidateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ValidateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ValidateRequest proto.InternalMessageInfo

func (m *ValidateRequest) GetIid() uint32 {
	if m != nil {
		return m.Iid
	}
	return 0
}

func (m *ValidateRequest) GetSession() string {
	if m != nil {
		return m.Session
	}
	return ""
}

type ValidateResponse struct {
	Ok                   bool     `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ValidateResponse) Reset()         { *m = ValidateResponse{} }
func (m *ValidateResponse) String() string { return proto.CompactTextString(m) }
func (*ValidateResponse) ProtoMessage()    {}
func (*ValidateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_gfalcon_4975e5dad6958583, []int{3}
}
func (m *ValidateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ValidateResponse.Unmarshal(m, b)
}
func (m *ValidateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ValidateResponse.Marshal(b, m, deterministic)
}
func (dst *ValidateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValidateResponse.Merge(dst, src)
}
func (m *ValidateResponse) XXX_Size() int {
	return xxx_messageInfo_ValidateResponse.Size(m)
}
func (m *ValidateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ValidateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ValidateResponse proto.InternalMessageInfo

func (m *ValidateResponse) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

func init() {
	proto.RegisterType((*SignInRequest)(nil), "SignInRequest")
	proto.RegisterType((*SignInResponse)(nil), "SignInResponse")
	proto.RegisterType((*ValidateRequest)(nil), "ValidateRequest")
	proto.RegisterType((*ValidateResponse)(nil), "ValidateResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// GfalconClient is the client API for Gfalcon service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GfalconClient interface {
	SignIn(ctx context.Context, in *SignInRequest, opts ...grpc.CallOption) (*SignInResponse, error)
	Validate(ctx context.Context, in *ValidateRequest, opts ...grpc.CallOption) (*ValidateResponse, error)
}

type gfalconClient struct {
	cc *grpc.ClientConn
}

func NewGfalconClient(cc *grpc.ClientConn) GfalconClient {
	return &gfalconClient{cc}
}

func (c *gfalconClient) SignIn(ctx context.Context, in *SignInRequest, opts ...grpc.CallOption) (*SignInResponse, error) {
	out := new(SignInResponse)
	err := c.cc.Invoke(ctx, "/Gfalcon/SignIn", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gfalconClient) Validate(ctx context.Context, in *ValidateRequest, opts ...grpc.CallOption) (*ValidateResponse, error) {
	out := new(ValidateResponse)
	err := c.cc.Invoke(ctx, "/Gfalcon/Validate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GfalconServer is the server API for Gfalcon service.
type GfalconServer interface {
	SignIn(context.Context, *SignInRequest) (*SignInResponse, error)
	Validate(context.Context, *ValidateRequest) (*ValidateResponse, error)
}

func RegisterGfalconServer(s *grpc.Server, srv GfalconServer) {
	s.RegisterService(&_Gfalcon_serviceDesc, srv)
}

func _Gfalcon_SignIn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignInRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GfalconServer).SignIn(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Gfalcon/SignIn",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GfalconServer).SignIn(ctx, req.(*SignInRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Gfalcon_Validate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GfalconServer).Validate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Gfalcon/Validate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GfalconServer).Validate(ctx, req.(*ValidateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Gfalcon_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Gfalcon",
	HandlerType: (*GfalconServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SignIn",
			Handler:    _Gfalcon_SignIn_Handler,
		},
		{
			MethodName: "Validate",
			Handler:    _Gfalcon_Validate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/gfalcon.proto",
}

func init() { proto.RegisterFile("proto/gfalcon.proto", fileDescriptor_gfalcon_4975e5dad6958583) }

var fileDescriptor_gfalcon_4975e5dad6958583 = []byte{
	// 230 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0x41, 0x4b, 0x03, 0x31,
	0x10, 0x85, 0xbb, 0xa9, 0xb4, 0xeb, 0x40, 0xb7, 0xeb, 0x78, 0x09, 0x7b, 0x92, 0x9c, 0x04, 0x21,
	0xa2, 0x9e, 0x3d, 0x8b, 0x20, 0x08, 0x11, 0xbc, 0x47, 0x13, 0x4b, 0x68, 0xcd, 0xac, 0x9d, 0x88,
	0x7f, 0x5f, 0x9a, 0x6e, 0x94, 0x2d, 0xbd, 0xcd, 0x0c, 0x7c, 0x5f, 0x5e, 0x1e, 0x9c, 0xf7, 0x5b,
	0x4a, 0x74, 0xbd, 0xfa, 0xb0, 0x9b, 0x77, 0x8a, 0x3a, 0x6f, 0xea, 0x19, 0x16, 0x2f, 0x61, 0x15,
	0x1f, 0xa3, 0xf1, 0x5f, 0xdf, 0x9e, 0x13, 0x22, 0x9c, 0x24, 0x6f, 0x3f, 0x65, 0x75, 0x51, 0x5d,
	0x9e, 0x9a, 0x3c, 0x63, 0x03, 0x22, 0x38, 0x29, 0xf2, 0x45, 0x04, 0x87, 0x1d, 0xd4, 0xbd, 0x65,
	0xfe, 0xa1, 0xad, 0x93, 0xd3, 0x7c, 0xfd, 0xdb, 0xd5, 0x13, 0x34, 0x45, 0xc8, 0x3d, 0x45, 0xf6,
	0x3b, 0x9a, 0xd6, 0xd9, 0x57, 0x1b, 0x41, 0x6b, 0x6c, 0x61, 0x1a, 0x06, 0xdd, 0xc2, 0xec, 0x46,
	0x94, 0x30, 0x67, 0xcf, 0x1c, 0x28, 0x0e, 0xba, 0xb2, 0xaa, 0x7b, 0x58, 0xbe, 0xda, 0x4d, 0x70,
	0x36, 0xf9, 0x12, 0x70, 0xc0, 0xab, 0xa3, 0xb8, 0x18, 0xe3, 0x0a, 0xda, 0x7f, 0xfc, 0x78, 0x9c,
	0xdb, 0x00, 0xf3, 0x87, 0x7d, 0x25, 0x78, 0x05, 0xb3, 0x7d, 0x76, 0x6c, 0xf4, 0xa8, 0x95, 0x6e,
	0xa9, 0xc7, 0x9f, 0x52, 0x13, 0xbc, 0x81, 0xba, 0xb8, 0xb1, 0xd5, 0x07, 0x29, 0xbb, 0x33, 0x7d,
	0xf8, 0xb0, 0x9a, 0xbc, 0xcd, 0x72, 0xe7, 0x77, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x46, 0xb8,
	0xb6, 0xee, 0x8a, 0x01, 0x00, 0x00,
}
